FROM python:3.9.1

RUN apt-get install wget
RUN pip install pandas sqlalchemy psycopg2

WORKDIR /app
COPY ingest_zone_data.py ingest_zone_data.py


ENTRYPOINT [ "python", "ingest_zone_data.py", "--user", "postgres", "--password", "postgres", "--host", "postgres", "--port", "5432", "--db", "ny_taxi", "--table_name", "zones", "--url", "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"]